name: Build and Test
on: [push]
jobs:
  Ubuntu-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          sudo add-apt-repository -y "deb http://archive.ubuntu.com/ubuntu `lsb_release -sc` main universe restricted multiverse"
          sudo apt-get update -y -qq
          sudo apt-get install libsdl2-dev

      - name: Build
        run: |
          make

      - name: Test
        run: |
          ls -alh ./risc

  MacOS-build:
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: | 
          brew install SDL2

      - name: Build
        run: |
          make

      - name: Test
        run: |
          ls -alh ./risc      

  Windows-build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          vcpkg install SDL2
          vcpkg install getopt
          
      - name: Build
        run: |
          cd src
          mv Makefile.vc Makefile
          cl -c -D_WIN32 -Zi -W4 -WX -D_CRT_SECURE_NO_WARNINGS -MD -DSTATIC_BUFSIZ= -DS_IRUSR=0 -DS_IWUSR=0 -wd4146  -wd4100 -wd4996 -nologo sdl-main.c

      - name: Test
        run: |
          dir
          dir src

